### ISSUE TITLE
[P1] Multiple Choice Prompt rendering doesn't support line breaks

### ISSUE THREAD

**Issue by PowerMyLearningConnect** [pie-framework/pie-elements#77]
Steps to reproduce:
- Enter text in the prompt field, and include line breaks to separate several paragraphs.

Expected: Line breaks entered and saved on the authoring/teacher side (left) should appear on rendering/student side (right).
Actual: Line breaks are removed when rendering the prompt, and paragraphs are hard to differentiate.

<img width="1077" alt="screen shot 2018-09-04 at 3 54 56 pm" src="https://user-images.githubusercontent.com/36770983/45054475-1bd11580-b05b-11e8-968d-c9e82716d093.png">

Can be reproduced here: https://pie-catalog-demo.herokuapp.com/element/@pie-element/multiple-choice

**Comment by edeustace** [comment]
fixed in downstream dependency: @pie-lib/editable-html@6.7.3 - please rebuild and check

**Comment by PowerMyLearningConnect** [comment]
@edeustace 
I tested this on the PIE demo site, and it still doesn't seem to be working for me. 
Should this change be reflected on the demo site?

![image](https://user-images.githubusercontent.com/36770983/46680118-58da7b80-cbb6-11e8-8a0b-95b59dc1e93e.png)
