### ISSUE TITLE
multiple-choice - Insert image button missing in prompt

### ISSUE THREAD

**Issue by alex-alberto** [pie-framework/pie-elements#8]
![image 10](https://user-images.githubusercontent.com/36770983/38053513-4915d9f4-32a2-11e8-8edb-84e0b81d26df.png)

**Comment by edeustace** [comment]
see pie-framework/pie-lib/issues/4

**Comment by edeustace** [comment]
This is fixed in pie-framework/pie-lib#4 now, just need to merge this into the dependent libraries. 
 @alex-alberto you can see the pie-lib fix here: https://pie-framework.github.io/pie-lib/editable-html/

**Comment by edeustace** [comment]
Fixed: https://pie-catalog-demo.herokuapp.com/element/@pie-element/multiple-choice?mode=dev

**Comment by alex-alberto** [comment]
@edeustace Thanks for tackling that quickly!

Although, I'm sorry if I'm missing something, but I still don't see the insert image button in the prompt field?
<img width="707" alt="screen shot 2018-04-25 at 4 50 10 pm" src="https://user-images.githubusercontent.com/36770983/39272031-c2df2d28-48a8-11e8-8287-764c02c5a6c4.png">

**Comment by edeustace** [comment]
@alex-alberto  - Can you clear your browser cache and try again?

**Comment by alex-alberto** [comment]
@edeustace works great, thanks so much!
