### ISSUE TITLE
[P1] Can't edit/save MC prompt in Firefox

### ISSUE THREAD

**Issue by PowerMyLearningConnect** [pie-framework/pie-elements#82]
This happens on both the pie demo site and inside our PowerMyLearning Connect integration, with slightly different behaviors described below and gifs attached for both.

STEPS TO REPRODUCE ISSUE ON PIE DEMO SITE
1- In Firefox, navigate to https://pie-catalog-demo.herokuapp.com/element/@pie-element/multiple-choice
2- Click into the prompt field to edit.
Expected behavior: the cursor is visible in the field, and user can type
Actual: the cursor doesn't appear, and the prompt field weirdly expands as user tries to click/move cursor around (see video 1)

![video 1 firefox-mc-pie](https://user-images.githubusercontent.com/36770983/45637696-28049c00-ba79-11e8-9501-af018657f62f.gif)

STEPS TO REPRODUCE ISSUE INSIDE POWERMYLEARNING CONNECT
1- In firefox, navigate to www.powermylearning.org
2- In top right corner, click on login, and enter the following credentials: user name: pie@gmail.com password: pieqa1
3- Navigate to the Questions page (within the Library section in the top nav).
4- Click on the New Question button in the top right corner.
5- Select Multiple Choice
6- Click on the prompt field, type some text, and click on the green checkmark to save it.
Expected: Prompt is saved.
Actual: It takes a few times before clicking on the check mark closes the edit field, and once it does, the field weirdly expands as user tries to move cursor around and click (see video 2).

![video 2 firefox-mc-issue-production](https://user-images.githubusercontent.com/36770983/45637689-20dd8e00-ba79-11e8-8ba5-0d6c81d76500.gif)

**Comment by lakatosandrei** [comment]
The issue should be fixed now.

**Comment by PowerMyLearningConnect** [comment]
@lakatosandrei @edeustace 

I am still seeing the issue in Firefox. ( I am using version 62.0.3 (64-bit))

![image](https://user-images.githubusercontent.com/36770983/46680414-0ea5ca00-cbb7-11e8-8731-e29899de568c.png)

**Comment by lakatosandrei** [comment]
@PowerMyLearningConnect 
Yeah, sorry about that, I managed to fix the issue but didn't update all packages with the latest version. Will do that tomorrow though.

**Comment by PowerMyLearningConnect** [comment]
@lakatosandrei @edeustace 
I am still seeing this issue. Should this be resolved on the PIE demo site? 

![image](https://user-images.githubusercontent.com/36770983/46894210-bc2c0e00-ce41-11e8-94db-247a03f42abc.png)
